---
title: "Analysis_Scratch"
author: "Team"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r}
library(readxl)
library(dplyr)
library(ggplot2)

monthly_encounters <- read_excel("KHSM Encounters (OFO) fy25m11.xlsx", sheet = "Monthly Count")

names(monthly_encounters)[1] <- "Fiscal_Year"

monthly_encounter_df <- monthly_encounters %>%
  group_by(Month) %>%
  summarize(Month_Mean = mean(Quantity, na.rm = TRUE))

monthly_encounter_df$Month <- factor(monthly_encounter_df$Month, levels = unique(monthly_encounter_df$Month))

ggplot(monthly_encounter_df, aes(x = Month, y = Month_Mean)) + 
  geom_point() +
  labs(title = "Key Homeland Security Metric - Office of Field Operations",
       x = "Month",
       y = "Monthly Average") +
  theme_minimal()

ggplot(monthly_encounter_df, aes(x = Month, y = Month_Mean, fill = Month_Mean)) +
  geom_bar(stat = "identity") +
  labs(title = "Key Homeland Security Metric - Office of Field Operations",
       x = "Month",
       y = "Monthly Average") +
  theme_minimal()



```






```{r echo=FALSE, warning=FALSE, fig.height=4, fig.width=10}


#-----------------Yearly Encounters by US Entry: 2014–2025-----------------

# 
# #Read Microsoft Excel files
# library(readxl)
# #Use ggplot
# library(ggplot2)
# 
# #Use dplyr and silence warnings
# library(dplyr, warn.conflicts = FALSE)
# options(dplyr.summarise.inform = FALSE)
# 
# 
# annual_region_encounters <- read_excel("KHSM Encounters (OFO) fy25m11.xlsx", 
#                                        sheet = "Annual Region")
# 
# 
# annual_region_encounters <- annual_region_encounters %>%
#   rename(
#     Year = 'Fiscal\r\nYear',
#     Region = 'Region', 
#     Encounters = 'Quantity'
#   ) %>%
#   filter(Year >= 2004 & Year <= 2024)
# 
# ggplot(annual_region_encounters, aes(x = Year, y = Encounters, color = Region)) +
#   geom_line(size = 1) +
#   geom_point(size = 2) +
#   
#   geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
#   geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
#   geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
#   geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
#   geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
#   geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +
# 
#   annotate("text", x = 2004, y = max(annual_region_encounters$Encounters) * 0.85, 
#            label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
#   annotate("text", x = 2012, y = max(annual_region_encounters$Encounters) * 0.85, 
#            label = "DACA", angle = 90, vjust = -0.4, size = 3) +
#   annotate("text", x = 2015, y = max(annual_region_encounters$Encounters) * 0.85, 
#            label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
#   annotate("text", x = 2020, y = max(annual_region_encounters$Encounters) * 0.85, 
#            label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
#   annotate("text", x = 2021, y = max(annual_region_encounters$Encounters) * 0.85, 
#            label = "Remain in Mexico Ends", angle = 90, vjust = -0.4, size = 3) +
#   annotate("text", x = 2023, y = max(annual_region_encounters$Encounters) * 0.85, 
#            label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +
#   
#   
#   labs(
#     title = "Yearly Encounters by US Entry: 2004–2024",
#     caption = "Source: KHSM Encounters (OFO)",
#     x = "Year",
#     y = "Encounters",
#     fill = "US Entry"
#   ) +
#   theme_minimal() +
#   theme(
#     legend.position = "right",
#     plot.title = element_text(face = "bold", size = 14)
#   )


```




```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)



# origins_of_interest <- c('Mexico', 'Canada', 'Haiti', 'Cuba', 'Philipines', 'Ukraine')
# 
# total_origin_encounters <- annual_origin_encounters %>%
#   #filter(Origin == origins_of_interest) %>%
#   group_by(Origin, Year) %>%
#   summarise(AvgEncounters = mean(Encounters)) %>%
#   ungroup()


#print(total_origin_encounters)


# total_by_year_2004 <- total_origin_encounters %>%
#   group_by(Year) %>%
#   arrange(Year, desc(Total)) %>%
#   slice_head(n=5) %>%
#   ungroup()


#print(total_by_year_2004)

# distinct_origins <- total_by_year_2004 %>%
#   dplyr::distinct(Origin) %>%
#   arrange(desc(Origin))
#print(distinct_origins)

#total_by_year <- spread(total_origin_encounters, key=Year, value=Total)
#print(total_by_year)






# top_total_origin_encounters <- annual_origin_encounters %>%
#   group_by(Year) %>%
#   arrange(Year, desc(Encounters)) %>%
#   slice_head(n=5) %>%
#   ungroup()

# 
#  # Create the scatterplot with boxplots
#  ggplot(top_total_origin_encounters, aes(x = Year, y = Encounters, color = Origin)) +
#    geom_point(alpha = 0.5) + # Scatterplot#
#    geom_boxplot(aes(group = Year), position = position_dodge(width = 5.8), 
#                 width = 0.2) + # Boxplots
#    labs(title = "Enconters by Year",
#       x = "Fiscal Year",
#       y = "Encounters") +
#    theme_minimal()


```





```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}

# library(readxl)
# library(dplyr)
# library(ggplot2)
# 
# #Use dplyr and silence warnings
# library(dplyr, warn.conflicts = FALSE)
# options(dplyr.summarise.inform = FALSE)
# 
# 
# # Load the data
# file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
# sheet_name <- "Annual Citizenship"
# df <- read_excel(file_path, sheet = sheet_name)
# 
# 
# annual_origin_encounters <- df %>%
#   rename(
#     Year = 'Fiscal\r\nYear',
#     Encounters = 'Quantity',
#     Origin = 'Citizenship'
#   )
# 
# 
# # Clean the data
# annual_origin_encounters <- annual_origin_encounters %>%
#   select(Year, Origin, Encounters) %>%
#   filter(!is.na(Origin) & !is.na(Encounters)) %>%
#   #filter(Year==2015) %>%
#   group_by(Origin, Year) %>%
#   summarise(AvgEncounters = mean(Encounters)) %>%
#   arrange(Year, desc(AvgEncounters)) %>%
#   slice_head(n=5) %>%
#   ungroup()
# 
# 
# annual_origin_encounters %>%
#   ggplot(aes(x=Year, y=AvgEncounters)) + #, color = Origin)) +
#   geom_point() +
#   
#   # Following 15 LOC are for political events.
#   geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
#   geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
#   geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
#   geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
#   geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +
# 
#   annotate("text", x = 2004, y = 200000, 
#           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
#   annotate("text", x = 2012, y = 200000, 
#           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
#   annotate("text", x = 2015, y = 200000, 
#           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
#   annotate("text", x = 2020, y = 200000, 
#           label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
#   annotate("text", x = 2023, y = 200000, 
#           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +
# 
#   labs(title = "Encounters by Origin (Total): 2004–2025",
#        caption = "Source: KHSM Encounters (OFO)",
#        x = "Encounters",
#        y = "Year") +
#   theme_minimal()


```



```{r}



# encounters <- 'KHSM Encounters (OFO) fy25m11.xlsx'
# family_encounters <- read_excel(encounters, sheet = 'Annual Family Status')
# 



# monthly_encounters %>%
#   ggplot(aes(x = Month, y = Month_Mean, fill = Month_Mean)) +
#   geom_bar(stat = "identity") +



# geom_text(aes(label = round(Month_Mean, 1)), vjust = -0.5, size = 3)
# 
# geom_smooth(method = "lm", se = FALSE, color = "purple", linetype = "dashed")



```




```{r echo=FALSE, warning=FALSE}

# 
# 
# #-----------------Scratch analysis-----------------
# 
# #Read Microsoft Excel files
# library(readxl)
# #Use ggplot
# library(ggplot2)
# 
# #Use dplyr and silence warnings
# library(dplyr, warn.conflicts = FALSE)
# options(dplyr.summarise.inform = FALSE)
# 
# 
# # Load the data
# file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
# sheet_name <- "Monthly Citizenship"
# df <- read_excel(file_path, sheet = sheet_name)
# 
# 
# 
# unique(annual_region_encounters$Region)
# 
# 
# monthly_origin_encounters <- df %>%
#   rename(
#     Year = 'Fiscal\r\nYear',
#     Encounters = 'Quantity',
#     Origin = 'Citizenship'
#   )
# 
# distinct_origins <- monthly_origin_encounters %>%
#   distinct(Origin)
# 
# origins_of_interest <- c('Mexico', 'El Salvador', 'Afghanistan')
# 
# # Clean the data
# top_origin_encounters <- monthly_origin_encounters %>%
#   select(Year, Month, Origin, Encounters) %>%
#   filter(!is.na(Origin) & !is.na(Encounters)) %>%
#   filter(Origin == origins_of_interest) %>%
#   #mutate(Year = as.integer(Year), Encounters = as.numeric(Encounters)) %>%
#   group_by(Origin, Year, Month) %>%
#   summarise(Total = sum(Encounters)) %>%
#   ungroup %>%
#   group_by(Origin, Year) %>%
#   summarise(TotalOrigin = sum(Total)) %>%
#   ungroup()
# 
# 





```






```{r echo=FALSE, warning=FALSE}

# library(ggplot2)
# 
# 
# 
# ggplot(top_origin_encounters, aes(x = Year, y = TotalOrigin, color = Origin)) +
#   geom_line(size = 1) +
#   geom_point(size = 2) +
#   labs(
#     title = "Spaghetti Plot: Border Encounters by Region (2014–2025)",
#     x = "Year",
#     y = "Encounters"
#   ) +
#   theme_minimal() +
#   theme(
#     legend.position = "right",
#     plot.title = element_text(face = "bold", size = 14)
#   )
# 
# 
#  # Create the scatterplot with boxplots
#  ggplot(top_origin_encounters, aes(x = Year, y = TotalOrigin, color = Origin)) +
#    geom_point(alpha = 0.5) + # Scatterplot#
#    geom_boxplot(aes(group = Year), position = position_dodge(width = 5.8), 
#                 width = 0.2) + # Boxplots
#    labs(title = "Scatterplot with Boxplots of Immigrants by Fiscal Year",
#       x = "Fiscal Year",
#       y = "Encounters") +
#    theme_minimal()
# 


```