

---
title: "Analysis - Yearly"
date: "`r Sys.Date()`"
output:
  html_document: default
---




```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------CBP Encounters by US Region: 2004–2024-----------------


#Read Microsoft Excel files
library(readxl)
#Use ggplot
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


annual_region_encounters <- read_excel("KHSM Encounters (OFO) fy25m11.xlsx", sheet = "Annual Region")


#Sanitize column headers and rename to more intelligible naming
#Filter to appropriate time frame
annual_region_encounters_sanitize <- annual_region_encounters %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Region = 'Region',
    Encounters = 'Quantity'
  ) %>%
  filter(Year >= 2004 & Year <= 2024)


#Sum encounters by region
annual_region_encounters <- annual_region_encounters_sanitize %>%
  group_by(Region, Year) %>%
  summarize(Total = sum(Encounters))


#Add a factor to help order the legend to match quantity of encounters heirarchy
annual_region_encounters <- annual_region_encounters %>%
  dplyr::filter(Region %in% c('Southwest Land Border', 'Air Ports of Entry/Interior', 'Northern Land Border',  'Coastal Border'))
annual_region_encounters$Region <- factor(annual_region_encounters$Region, levels=c('Southwest Land Border', 'Air Ports of Entry/Interior', 'Northern Land Border', 'Coastal Border'))


#Option to not use scientific notation
options(scipen=999)


#Plot spaghetti plot to contrast regional encounters
ggplot(annual_region_encounters, aes(x = Year, y = Total, color = Region)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +

  #Add US policy events
  geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +

  annotate("text", x = 2004, y = max(annual_region_encounters$Total) * 0.85,
           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2012, y = max(annual_region_encounters$Total) * 0.85,
           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2015, y = max(annual_region_encounters$Total) * 0.85,
           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2020, y = max(annual_region_encounters$Total) * 0.85,
           label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2021, y = max(annual_region_encounters$Total) * 0.8,
           label = "Remain in Mexico Ends", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2023, y = max(annual_region_encounters$Total) * 0.85,
           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +

labs(
    title = "CBP Encounters by Region: 2004–2024",
    subtitle = "Policy milestones overlaid to reflect spikes and dips in migration trends",
    caption = "Source: Office of Homeland Security Statistics - Customs & Border Patrol Encounters",
    x = "Year",
    y = "Encounters",
    fill = "US Entry"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(color = 'grey', fill = NA, size = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 12),
    plot.caption = element_text(size = 9)
  )

```




```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------CBP Encounters by Top Origins: 2004–2025-----------------


#Read Microsoft Excel files
library(readxl)
#Use ggplot
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


# Load the data
file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
sheet_name <- "Annual Citizenship"
annual_origin_encounters <- read_excel(file_path, sheet = sheet_name)

#Sanitize column headers and rename to more intelligible naming
#Filter to appropriate time frame
annual_origin_encounters_sanitize <- annual_origin_encounters %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Encounters = 'Quantity',
    Origin = 'Citizenship'
  ) %>%
  filter(Year >= 2004 & Year <= 2024)


# Determine the top countries by total citizenships granted
annual_origin_encounters_filtered <- annual_origin_encounters_sanitize %>%
  group_by(Origin) %>%
  summarise(Total = sum(Encounters)) %>%
  arrange(desc(Total)) %>%
  slice_head(n=5)


# Filter the original data to include only these top countries
top_annual_origin_encounters <- annual_origin_encounters_sanitize %>%
  filter(Origin %in% annual_origin_encounters_filtered$Origin) %>%
  group_by(Origin, Year) %>%
  summarise(Total = sum(Encounters))


#Add a factor to help order the legend to match quantity of encounters heirarchy
top_annual_origin_encounters <- top_annual_origin_encounters %>%
  dplyr::filter(Origin %in% c('Haiti', 'Cuba', 'Mexico',  'Philippines', 'Canada'))
top_annual_origin_encounters$Origin <- factor(top_annual_origin_encounters$Origin, levels=c('Haiti', 'Cuba', 'Mexico',  'Philippines', 'Canada'))


#Plot spaghetti plot to contrast encounters by origin
ggplot(top_annual_origin_encounters, aes(x = Year, y = Total, color = Origin)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  
  #Add US policy events
  geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +

  annotate("text", x = 2004, y = max(top_annual_origin_encounters$Total) * 0.85, 
           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2012, y = max(top_annual_origin_encounters$Total) * 0.85, 
           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2015, y = max(top_annual_origin_encounters$Total) * 0.85, 
           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2020, y = max(top_annual_origin_encounters$Total) * 0.85, 
           label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2021, y = max(top_annual_origin_encounters$Total) * 0.85, 
           label = "Remain in Mexico Ends", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2023, y = max(top_annual_origin_encounters$Total) * 0.85, 
           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +
  
  labs(
    title = "CBP Encounters by Top Origins: 2004–2025",
    caption = "Source: Office of Homeland Security Statistics - Customs & Border Patrol Encounters",
    x = "Year",
    y = "Encounters"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(color = 'grey', fill = NA, size = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 14)
  )


```




```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------CBP Encounters by Top Origins: 2004–2025----------------



library(readxl)
library(dplyr)
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


# Load the data
file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
sheet_name <- "Annual Family Status"
annual_familystatus_encounters <- read_excel(file_path, sheet = sheet_name)


#Sanitize column headers and rename to more intelligible naming
#Filter to appropriate time frame
annual_familystatus_encounters_sanitize <- annual_familystatus_encounters %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Encounters = 'Quantity',
    Family = 'Family Status'
  ) %>%
  filter(Year >= 2004 & Year <= 2024)


# Summarize the data to get the sum of quantities for each family status by year
annual_familystatus_encounters <- annual_familystatus_encounters_sanitize %>%
  group_by(Year, Family) %>%
  summarize(Total = sum(Encounters))


# Create the bar chart
ggplot(annual_familystatus_encounters, aes(x = Year, y = Total, fill = Family)) +
  geom_bar(stat = 'identity') +
  
  geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +

  annotate("text", x = 2004, y = max(annual_familystatus_encounters$Total) * 0.85, 
           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2012, y = max(annual_familystatus_encounters$Total) * 0.85, 
           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2015, y = max(annual_familystatus_encounters$Total) * 0.85, 
           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2020, y = max(annual_familystatus_encounters$Total) * 0.85, 
           label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2021, y = max(annual_familystatus_encounters$Total) * 0.85, 
           label = "Remain in Mexico Ends", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2023, y = max(annual_familystatus_encounters$Total) * 0.85, 
           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +
  
  labs(title = 'CBP Encounters by Top Origins: 2004–2025',
       x = 'Year',
       y = 'Encounters',
       fill = 'Family Status') +
  theme_minimal() +
  theme(
    panel.border = element_rect(color = 'grey', fill = NA, size = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 14)
  )


```




```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------CBP Encounters by US Region: 2004–2024-----------------


#Read Microsoft Excel files
library(readxl)
#Use ggplot
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


annual_region_encounters <- read_excel("KHSM Encounters (OFO) fy25m11.xlsx", sheet = "Annual Region")


#Sanitize column headers and rename to more intelligible naming
#Filter to appropriate time frame
annual_region_encounters_sanitize <- annual_region_encounters %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Region = 'Region',
    Encounters = 'Quantity'
  ) %>%
  filter(Year >= 2004 & Year <= 2024)


#Sum encounters by region
annual_region_encounters <- annual_region_encounters_sanitize %>%
  group_by(Region, Year) %>%
  summarize(Total = sum(Encounters))


#Add a factor to help order the legend to match quantity of encounters heirarchy
annual_region_encounters <- annual_region_encounters %>%
  dplyr::filter(Region %in% c('Southwest Land Border', 'Air Ports of Entry/Interior', 'Northern Land Border',  'Coastal Border'))
annual_region_encounters$Region <- factor(annual_region_encounters$Region, levels=c('Southwest Land Border', 'Air Ports of Entry/Interior', 'Northern Land Border', 'Coastal Border'))


#Option to not use scientific notation
options(scipen=999)


#Plot spaghetti plot to contrast regional encounters
ggplot(annual_region_encounters, aes(x = Year, y = Total, color = Region)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +

  #Add US policy events
  geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +

  annotate("text", x = 2004, y = max(annual_region_encounters$Total) * 0.85,
           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2012, y = max(annual_region_encounters$Total) * 0.85,
           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2015, y = max(annual_region_encounters$Total) * 0.85,
           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2020, y = max(annual_region_encounters$Total) * 0.85,
           label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2021, y = max(annual_region_encounters$Total) * 0.8,
           label = "Remain in Mexico Ends", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2023, y = max(annual_region_encounters$Total) * 0.85,
           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +

labs(
    title = "CBP Encounters by Region: 2004–2024",
    subtitle = "Policy milestones overlaid to reflect spikes and dips in migration trends",
    caption = "Source: Office of Homeland Security Statistics - Customs & Border Patrol Encounters",
    x = "Year",
    y = "Encounters",
    fill = "US Entry"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(color = 'grey', fill = NA, size = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 12),
    plot.caption = element_text(size = 9)
  )

```





```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------Regional (facet) - CBP Encounters by Family Status: 2004–2025----------


#Read Microsoft Excel files
library(readxl)
#Use ggplot
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


# Load the data
file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
sheet_name <- "Annual Rgn EnfAdm Fam Status"
annual_region_famstat_encounters <- read_excel(file_path, sheet = sheet_name)

#Sanitize column headers and rename to more intelligible naming
#Filter to appropriate time frame
annual_region_famstat_encounters_sanitize <- annual_region_famstat_encounters %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Encounters = 'Quantity',
    Family = 'Family Status'
  ) %>%
  filter(Year >= 2004 & Year <= 2024)


#Filter the original data to for analysis by Northern Land Border
annual_region_famstat_encounters_northern <- annual_region_famstat_encounters_sanitize %>%
  filter(Region == c('Northern Land Border'))
#Find Total this Region and then add Region back to dataset
annual_region_famstat_encounters_northern <- annual_region_famstat_encounters_northern %>%
  group_by(Family, Year) %>%
  summarise(Total = sum(Encounters)) %>%
  mutate(Region = 'Northern Land Border')


#Filter the original data to for analysis by Air Ports of Entry/Interior
annual_region_famstat_encounters_airport <- annual_region_famstat_encounters_sanitize %>%
  filter(Region == c('Air Ports of Entry/Interior'))
#Find Total this Region and then add Region back to dataset
annual_region_famstat_encounters_airport <- annual_region_famstat_encounters_airport %>%
  group_by(Family, Year) %>%
  summarise(Total = sum(Encounters)) %>%
  mutate(Region = 'Air Ports of Entry/Interior')


#Filter the original data to for analysis by Southwest Land Border
annual_region_famstat_encounters_southwest <- annual_region_famstat_encounters_sanitize %>%
  filter(Region == c('Southwest Land Border'))
#Find Total this Region and then add Region back to dataset
annual_region_famstat_encounters_southwest <- annual_region_famstat_encounters_southwest %>%
  group_by(Family, Year) %>%
  summarise(Total = sum(Encounters)) %>%
  mutate(Region = 'Southwest Land Border')


#Filter the original data to for analysis by Coastal Border
annual_region_famstat_encounters_coastal <- annual_region_famstat_encounters_sanitize %>%
  filter(Region == c('Coastal Border'))
#Find Total this Region and then add Region back to dataset
annual_region_famstat_encounters_coastal <- annual_region_famstat_encounters_coastal %>%
  group_by(Family, Year) %>%
  summarise(Total = sum(Encounters)) %>%
  mutate(Region = 'Coastal Border')



#Union all Regional analysis to be used in Facet Wrap
annual_region_famstat_encounters_all <- bind_rows(annual_region_famstat_encounters_northern, annual_region_famstat_encounters_airport, annual_region_famstat_encounters_southwest, annual_region_famstat_encounters_coastal)


#Add a factor to help order the facet wrap
annual_region_famstat_encounters_all <- annual_region_famstat_encounters_all %>%
  dplyr::filter(Region %in% c('Southwest Land Border', 'Air Ports of Entry/Interior', 'Northern Land Border',  'Coastal Border'))
annual_region_famstat_encounters_all$Region <- factor(annual_region_famstat_encounters_all$Region, levels=c('Southwest Land Border', 'Air Ports of Entry/Interior', 'Northern Land Border', 'Coastal Border'))


#Add a factor to help order legend
annual_region_famstat_encounters_all <- annual_region_famstat_encounters_all %>%
  dplyr::filter(Family %in% c('Single Adults', 'Family Unit Individuals', 'Unaccompanied Children',  'Accompanied Minors'))
annual_region_famstat_encounters_all$Family <- factor(annual_region_famstat_encounters_all$Family, levels=c('Single Adults', 'Family Unit Individuals', 'Unaccompanied Children', 'Accompanied Minors'))



#Plot spaghetti plot to contrast encounters by origin
ggplot(annual_region_famstat_encounters_all, aes(x = Year, y = Total, color = Family)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  facet_wrap(~ Region) +
  
  #Add US policy events
  geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +

  annotate("text", x = 2004, y = max(annual_region_famstat_encounters_all$Total) * 0.65, 
           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2012, y = max(annual_region_famstat_encounters_all$Total) * 0.65, 
           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2015, y = max(annual_region_famstat_encounters_all$Total) * 0.65, 
           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2020, y = max(annual_region_famstat_encounters_all$Total) * 0.65, 
           label = "COVID+Title 42", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2021, y = max(annual_region_famstat_encounters_all$Total) * 0.65, 
           label = "Rem In Mex Ends", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2023, y = max(annual_region_famstat_encounters_all$Total) * 0.65, 
           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +


  labs(
    title = "Regional - CBP Encounters by Family Status: 2004–2025",
    caption = "Source: Office of Homeland Security Statistics - Customs & Border Patrol Encounters",
    x = "Year",
    y = "Encounters"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(color = 'grey', fill = NA, size = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 14)
  )


```








```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------Northern Region - CBP Encounters by Family Status: 2004–2025----------


#Read Microsoft Excel files
library(readxl)
#Use ggplot
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


# Load the data
file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
sheet_name <- "Annual Rgn EnfAdm Fam Status"
annual_region_famstat_encounters <- read_excel(file_path, sheet = sheet_name)

#Sanitize column headers and rename to more intelligible naming
#Filter to appropriate time frame
annual_region_famstat_encounters_sanitize <- annual_region_famstat_encounters %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Encounters = 'Quantity',
    Family = 'Family Status'
  ) %>%
  filter(Year >= 2004 & Year <= 2024)


annual_region_famstat_encounters_northern <- annual_region_famstat_encounters_sanitize %>%
  filter(Region == c('Northern Land Border'))


# Filter the original data to include only these top countries
annual_region_famstat_encounters_northern <- annual_region_famstat_encounters_northern %>%
  #filter(Origin %in% annual_origin_encounters_filtered$Origin) %>%
  group_by(Family, Year) %>%
  summarise(Total = sum(Encounters))


#Plot spaghetti plot to contrast encounters by origin
ggplot(annual_region_famstat_encounters_northern, aes(x = Year, y = Total, color = Family)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  
  #Add US policy events
  geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +

  annotate("text", x = 2004, y = max(annual_region_famstat_encounters_northern$Total) * 0.85, 
           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2012, y = max(annual_region_famstat_encounters_northern$Total) * 0.85, 
           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2015, y = max(annual_region_famstat_encounters_northern$Total) * 0.85, 
           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2020, y = max(annual_region_famstat_encounters_northern$Total) * 0.85, 
           label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2021, y = max(annual_region_famstat_encounters_northern$Total) * 0.85, 
           label = "Remain in Mexico Ends", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2023, y = max(annual_region_famstat_encounters_northern$Total) * 0.85, 
           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +
  
  labs(
    title = "Northern Region - CBP Encounters by Family Status: 2004–2025",
    caption = "Source: Office of Homeland Security Statistics - Customs & Border Patrol Encounters",
    x = "Year",
    y = "Encounters"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(color = 'grey', fill = NA, size = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 14)
  )


```




```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------Airport/Interior Region - CBP Encounters by Family Status:  2004–2025------------


#Read Microsoft Excel files
library(readxl)
#Use ggplot
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


# Load the data
file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
sheet_name <- "Annual Rgn EnfAdm Fam Status"
annual_region_famstat_encounters <- read_excel(file_path, sheet = sheet_name)

#Sanitize column headers and rename to more intelligible naming
#Filter to appropriate time frame
annual_region_famstat_encounters_sanitize <- annual_region_famstat_encounters %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Encounters = 'Quantity',
    Family = 'Family Status'
  ) %>%
  filter(Year >= 2004 & Year <= 2024)


annual_region_famstat_encounters_airport <- annual_region_famstat_encounters_sanitize %>%
  filter(Region == c('Air Ports of Entry/Interior'))


# Filter the original data to include only these top countries
annual_region_famstat_encounters_airport <- annual_region_famstat_encounters_airport %>%
  #filter(Origin %in% annual_origin_encounters_filtered$Origin) %>%
  group_by(Family, Year) %>%
  summarise(Total = sum(Encounters))


#Plot spaghetti plot to contrast encounters by origin
ggplot(annual_region_famstat_encounters_airport, aes(x = Year, y = Total, color = Family)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  
  #Add US policy events
  geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +

  annotate("text", x = 2004, y = max(annual_region_famstat_encounters_airport$Total) * 0.85, 
           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2012, y = max(annual_region_famstat_encounters_airport$Total) * 0.85, 
           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2015, y = max(annual_region_famstat_encounters_airport$Total) * 0.85, 
           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2020, y = max(annual_region_famstat_encounters_airport$Total) * 0.85, 
           label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2021, y = max(annual_region_famstat_encounters_airport$Total) * 0.85, 
           label = "Remain in Mexico Ends", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2023, y = max(annual_region_famstat_encounters_airport$Total) * 0.85, 
           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +
  
  labs(
    title = "Airport/Interior Region - CBP Encounters by Family Status: 2004–2025",
    x = "Year",
    y = "Encounters"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(color = 'grey', fill = NA, size = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 14)
  )


```




```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------Southwest Region - CBP Encounters by Family Status: 2004–2025-----------------


#Read Microsoft Excel files
library(readxl)
#Use ggplot
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


# Load the data
file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
sheet_name <- "Annual Rgn EnfAdm Fam Status"
annual_region_famstat_encounters <- read_excel(file_path, sheet = sheet_name)

#Sanitize column headers and rename to more intelligible naming
#Filter to appropriate time frame
annual_region_famstat_encounters_sanitize <- annual_region_famstat_encounters %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Encounters = 'Quantity',
    Family = 'Family Status'
  ) %>%
  filter(Year >= 2004 & Year <= 2024)


annual_region_famstat_encounters_southwest <- annual_region_famstat_encounters_sanitize %>%
  filter(Region == c('Southwest Land Border'))


# Filter the original data to include only these top countries
annual_region_famstat_encounters_southwest <- annual_region_famstat_encounters_southwest %>%
  #filter(Origin %in% annual_origin_encounters_filtered$Origin) %>%
  group_by(Family, Year) %>%
  summarise(Total = sum(Encounters))


#Plot spaghetti plot to contrast encounters by origin
ggplot(annual_region_famstat_encounters_southwest, aes(x = Year, y = Total, color = Family)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  
  #Add US policy events
  geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +

  annotate("text", x = 2004, y = max(annual_region_famstat_encounters_southwest$Total) * 0.85, 
           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2012, y = max(annual_region_famstat_encounters_southwest$Total) * 0.85, 
           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2015, y = max(annual_region_famstat_encounters_southwest$Total) * 0.85, 
           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2020, y = max(annual_region_famstat_encounters_southwest$Total) * 0.85, 
           label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2021, y = max(annual_region_famstat_encounters_southwest$Total) * 0.85, 
           label = "Remain in Mexico Ends", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2023, y = max(annual_region_famstat_encounters_southwest$Total) * 0.85, 
           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +
  
  labs(
    title = 'Southwest Region - CBP Encounters by Family Status: 2004–2025',
    x = "Year",
    y = "Encounters"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(color = 'grey', fill = NA, size = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 14)
  )


```




```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------Coastal Border - CBP Encounters by Family Status: 2004–2025-----------------


#Read Microsoft Excel files
library(readxl)
#Use ggplot
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


# Load the data
file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
sheet_name <- "Annual Rgn EnfAdm Fam Status"
annual_region_famstat_encounters <- read_excel(file_path, sheet = sheet_name)

#Sanitize column headers and rename to more intelligible naming
#Filter to appropriate time frame
annual_region_famstat_encounters_sanitize <- annual_region_famstat_encounters %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Encounters = 'Quantity',
    Family = 'Family Status'
  ) %>%
  filter(Year >= 2004 & Year <= 2024)


annual_region_famstat_encounters_coastal <- annual_region_famstat_encounters_sanitize %>%
  filter(Region == c('Coastal Border'))


# Filter the original data to include only these top countries
annual_region_famstat_encounters_coastal <- annual_region_famstat_encounters_coastal %>%
  #filter(Origin %in% annual_origin_encounters_filtered$Origin) %>%
  group_by(Family, Year) %>%
  summarise(Total = sum(Encounters))


#Plot spaghetti plot to contrast encounters by origin
ggplot(annual_region_famstat_encounters_coastal, aes(x = Year, y = Total, color = Family)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  
  #Add US policy events
  geom_vline(xintercept = 2004, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2015, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2020, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2021, linetype = "dashed", color = "gray30") +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "gray30") +

  annotate("text", x = 2004, y = max(annual_region_famstat_encounters_coastal$Total) * 0.85, 
           label = "DHS Begins", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2012, y = max(annual_region_famstat_encounters_coastal$Total) * 0.85, 
           label = "DACA", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2015, y = max(annual_region_famstat_encounters_coastal$Total) * 0.85, 
           label = "Family Surge", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2020, y = max(annual_region_famstat_encounters_coastal$Total) * 0.85, 
           label = "COVID + Title 42", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2021, y = max(annual_region_famstat_encounters_coastal$Total) * 0.85, 
           label = "Remain in Mexico Ends", angle = 90, vjust = -0.4, size = 3) +
  annotate("text", x = 2023, y = max(annual_region_famstat_encounters_coastal$Total) * 0.85, 
           label = "Title 42 Ends", angle = 90, vjust = -0.4, size = 3) +
  
  labs(
    title = 'Coastal Border Region - CBP Encounters by Family Status: 2004–2025',
    x = "Year",
    y = "Encounters"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(color = 'grey', fill = NA, size = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 14)
  )


```




```{r echo=FALSE, warning=FALSE, fig.width=8, fig.height=4.5}


#-----------------Top 5 Encounters by Origin: 2004–2025-----------------



#Read Microsoft Excel files
library(readxl)
#Use ggplot
library(ggplot2)

#Use dplyr and silence warnings
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)


# Load the data
file_path <- "KHSM Encounters (OFO) fy25m11.xlsx"
sheet_name <- "Annual Citizenship"
df <- read_excel(file_path, sheet = sheet_name)

df <- df %>%
  rename(
    Year = 'Fiscal\r\nYear',
    Encounters = 'Quantity',
    Origin = 'Citizenship'
  )

# Determine the top countries by total citizenships granted
top_countries <- df %>%
  group_by(Origin) %>%
  summarise(Total = sum(Encounters)) %>%
  arrange(desc(Total)) %>%
  slice_head(n=5)

# Filter the original data to include only these top countries
top_origin_encounters <- df %>%
  filter(Origin %in% top_countries$Origin)


ggplot(top_origin_encounters, aes(x = Origin, y = Encounters)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Top 5 Encounters by Origin: 2004–2025",
       caption = "Source: Office of Homeland Security Statistics - Customs & Border Patrol Encounters",
       x = "Origin",
       y = "Encounters")


```








