---
title: "TestFileRmd2"
Group Name: Athens 2025
Members: Precious Merenu 
         Claudia Dominguez
         Justin Perez

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("readxl")
library(readxl)
```


```{r}
#Installing ggplot to visualize the data. 
install.packages("ggplot2", dependencies = T) 


```
#Trying to create a plot of the data. 

```{r}
library(readxl)
library(dplyr)
library(ggplot2)

monthly_encounters <- read_excel("KHSM Encounters (OFO) fy25m11.xlsx", sheet = "Monthly Count")

names(monthly_encounters)[1] <- "Fiscal_Year"

monthly_encounter_df <- monthly_encounters %>%
  group_by(Month) %>%
  summarize(Month_Mean = mean(Quantity, na.rm = TRUE))

monthly_encounter_df$Month <- factor(monthly_encounter_df$Month, levels = unique(monthly_encounter_df$Month))

ggplot(monthly_encounter_df, aes(x = Month, y = Month_Mean)) + 
  geom_point() +
  labs(title = "Key Homeland Security Metric - Office of Field Operations",
       x = "Month",
       y = "Monthly Average") +
  theme_minimal()

ggplot(monthly_encounter_df, aes(x = Month, y = Month_Mean, fill = Month_Mean)) +
  geom_bar(stat = "identity") +
  labs(title = "Key Homeland Security Metric - Office of Field Operations",
       x = "Month",
       y = "Monthly Average") +
  theme_minimal()



```