---
title: "Testrmdfile"
Group Name: Athens 2025
Members: Precious Merenu 
         Claudia Dominguez
         Justin Perez
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("readxl")
library(readxl)
```

```{r}
encounters <- 'KHSM Encounters (OFO) fy25m11.xlsx'
excel_sheets(encounters)

monthly_encounters <- read_excel(encounters, sheet = 'Monthly Count')

monthly_encounter_df <- monthly_encounters %>% mutate(Fiscal_Year='Fiscal Year') %>%
  group_by(Month) %>%
  summarize(Month_Mean = mean(Quantity))

print(monthly_encounter_df)

monthly_encounter_df %>% 
  ggplot(aes(x=Month, y=Month_Mean)) + 
  geom_point() +
  labs(title = "Key Homeland Security Metric - Office of Field Operations",
       x = "Month",
       y = "Monthly Average") +
  theme_minimal()

monthly_encounter_df %>%
  ggplot(aes(x = Month, y=Month_Mean, fill=Month_Mean)) +
  geom_bar(stat = "identity") +
  labs(title = "Key Homeland Security Metric - Office of Field Operations ",
       x = "Month",
       y = "Monthly Average",) +
  theme_minimal()


```


```{r}


health_data <- read_csv('DQS_NHIS_Children_Summary_Statistics_20250410.csv')
health_data %>% select(CLASSIFICATION)
print(health_data)







```
